<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="14" passed="10" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-02-28T14:34:04 AEDT" name="All Test Suite" finished-at="2022-02-28T14:35:35 AEDT" duration-ms="91106">
    <groups>
    </groups>
    <test started-at="2022-02-28T14:34:04 AEDT" name="chrometest" finished-at="2022-02-28T14:34:48 AEDT" duration-ms="43718">
      <class name="Tests.Plaint_work">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:Tests.Plaint_work@3e34ace1]" started-at="2022-02-28T14:34:04 AEDT" name="setup" finished-at="2022-02-28T14:34:06 AEDT" duration-ms="2275" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="UI_Test1()[pri:0, instance:Tests.Plaint_work@3e34ace1]" started-at="2022-02-28T14:34:06 AEDT" name="UI_Test1" finished-at="2022-02-28T14:34:10 AEDT" duration-ms="4077" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at POM.ContactPage.submitWithoutMandatory(ContactPage.java:60)
at Tests.Plaint_work.UI_Test1(Plaint_work.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UI_Test1 -->
        <test-method signature="UI_Test3()[pri:0, instance:Tests.Plaint_work@3e34ace1]" started-at="2022-02-28T14:34:06 AEDT" name="UI_Test3" finished-at="2022-02-28T14:34:40 AEDT" duration-ms="33748" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at POM.CartPage.verifyCartData(CartPage.java:53)
at Tests.Plaint_work.UI_Test3(Plaint_work.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UI_Test3 -->
        <test-method signature="UI_Test2()[pri:0, instance:Tests.Plaint_work@3e34ace1]" started-at="2022-02-28T14:34:06 AEDT" name="UI_Test2" finished-at="2022-02-28T14:34:21 AEDT" duration-ms="15082" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UI_Test2 -->
        <test-method signature="UI_Test2()[pri:0, instance:Tests.Plaint_work@3e34ace1]" started-at="2022-02-28T14:34:21 AEDT" name="UI_Test2" finished-at="2022-02-28T14:34:27 AEDT" duration-ms="5138" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UI_Test2 -->
        <test-method signature="UI_Test2()[pri:0, instance:Tests.Plaint_work@3e34ace1]" started-at="2022-02-28T14:34:27 AEDT" name="UI_Test2" finished-at="2022-02-28T14:34:29 AEDT" duration-ms="2072" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UI_Test2 -->
        <test-method signature="UI_Test2()[pri:0, instance:Tests.Plaint_work@3e34ace1]" started-at="2022-02-28T14:34:29 AEDT" name="UI_Test2" finished-at="2022-02-28T14:34:36 AEDT" duration-ms="7195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UI_Test2 -->
        <test-method signature="UI_Test2()[pri:0, instance:Tests.Plaint_work@3e34ace1]" started-at="2022-02-28T14:34:36 AEDT" name="UI_Test2" finished-at="2022-02-28T14:34:48 AEDT" duration-ms="11790" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UI_Test2 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Plaint_work@3e34ace1]" started-at="2022-02-28T14:34:48 AEDT" name="tearDown" finished-at="2022-02-28T14:34:48 AEDT" duration-ms="136" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Plaint_work -->
    </test> <!-- chrometest -->
    <test started-at="2022-02-28T14:34:48 AEDT" name="edgetest" finished-at="2022-02-28T14:35:35 AEDT" duration-ms="47348">
      <class name="Tests.Plaint_work">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:Tests.Plaint_work@74cadd41]" started-at="2022-02-28T14:34:48 AEDT" name="setup" finished-at="2022-02-28T14:34:49 AEDT" duration-ms="1292" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="UI_Test1()[pri:0, instance:Tests.Plaint_work@74cadd41]" started-at="2022-02-28T14:34:49 AEDT" name="UI_Test1" finished-at="2022-02-28T14:34:53 AEDT" duration-ms="3896" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at POM.ContactPage.submitWithoutMandatory(ContactPage.java:60)
at Tests.Plaint_work.UI_Test1(Plaint_work.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UI_Test1 -->
        <test-method signature="UI_Test3()[pri:0, instance:Tests.Plaint_work@74cadd41]" started-at="2022-02-28T14:34:49 AEDT" name="UI_Test3" finished-at="2022-02-28T14:35:23 AEDT" duration-ms="33577" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at POM.CartPage.verifyCartData(CartPage.java:53)
at Tests.Plaint_work.UI_Test3(Plaint_work.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UI_Test3 -->
        <test-method signature="UI_Test2()[pri:0, instance:Tests.Plaint_work@74cadd41]" started-at="2022-02-28T14:34:49 AEDT" name="UI_Test2" finished-at="2022-02-28T14:35:02 AEDT" duration-ms="13326" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UI_Test2 -->
        <test-method signature="UI_Test2()[pri:0, instance:Tests.Plaint_work@74cadd41]" started-at="2022-02-28T14:35:02 AEDT" name="UI_Test2" finished-at="2022-02-28T14:35:08 AEDT" duration-ms="5647" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UI_Test2 -->
        <test-method signature="UI_Test2()[pri:0, instance:Tests.Plaint_work@74cadd41]" started-at="2022-02-28T14:35:08 AEDT" name="UI_Test2" finished-at="2022-02-28T14:35:14 AEDT" duration-ms="6166" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UI_Test2 -->
        <test-method signature="UI_Test2()[pri:0, instance:Tests.Plaint_work@74cadd41]" started-at="2022-02-28T14:35:14 AEDT" name="UI_Test2" finished-at="2022-02-28T14:35:16 AEDT" duration-ms="2035" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UI_Test2 -->
        <test-method signature="UI_Test2()[pri:0, instance:Tests.Plaint_work@74cadd41]" started-at="2022-02-28T14:35:16 AEDT" name="UI_Test2" finished-at="2022-02-28T14:35:35 AEDT" duration-ms="18491" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UI_Test2 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Plaint_work@74cadd41]" started-at="2022-02-28T14:35:35 AEDT" name="tearDown" finished-at="2022-02-28T14:35:35 AEDT" duration-ms="372" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Plaint_work -->
    </test> <!-- edgetest -->
  </suite> <!-- All Test Suite -->
</testng-results>
